### ISSUE TITLE
Kill python process

### ISSUE THREAD

**Issue by benhylau** [tomeshnet/tomesh.mini#2]
@uditvira I think the line is messed up here, that's why it didn't kill the process properly:
https://github.com/tomeshnet/tomesh.mini/blob/master/game-board/code/start#L1

**Comment by uditvira** [comment]
Yes. It should be: `ps -ax | grep python | awk '{print $1}' | xargs kill -9 ; python main.py`

**Comment by ansuz** [comment]
:+1: to killing python.
![](http://i3.kym-cdn.com/photos/images/newsfeed/000/247/207/813.gif)

**Comment by benhylau** [comment]
lol I know what happened. I probably echo'd the line into a file when I was in a hurry to leave the house and the `$1` got replaced by well... nothing.

**Comment by benhylau** [comment]
Python is ded
